#!/usr/bin/env python3
"""wait_random function"""
from typing import List
import asyncio
from random import uniform
wait_random = __import__('0-basic_async_syntax').wait_random


async def task_wait_n(n: int, max_delay: int) -> List[float]:
    """
    return List of random delays generated by task_wait_random.
    """
    res = []
    for _ in range(n):
        delay = await task_wait_random(max_delay)
        res.append(delay)
    return sorted(res)
